# Generated by Django 2.2.3 on 2021-05-26 18:18

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('oferta', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('xl', 'XL'), ('l', 'L'), ('md', 'MD'), ('m', 'M'), ('s', 'S'), ('xs', 'XS')], default='xl', max_length=10, null=True)),
                ('articulo', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Productos')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('green', 'VERDE'), ('blue', 'AZUL'), ('red', 'ROJO'), ('orange', 'ANARANJADO'), ('black', 'NEGRO'), ('pink', 'ROSA')], default='green', max_length=30, null=True)),
                ('articulo', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Marca'),
        ),
    ]
