# Generated by Django 2.2.3 on 2021-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='count_vendido',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='articulo',
            name='masVendido',
            field=models.BooleanField(default=False),
        ),
    ]
