# Generated by Django 2.2.3 on 2021-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_auto_20210526_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Productos'),
        ),
    ]
