# Generated by Django 2.2.3 on 2021-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_articulo_img_mostrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='newProduct',
            field=models.BooleanField(default=False),
        ),
    ]
