# Generated by Django 2.2.3 on 2021-07-29 20:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_auto_20210729_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanio',
            name='tamanio',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('xl', 'XL'), ('l', 'L'), ('md', 'MD'), ('m', 'M'), ('s', 'S'), ('xs', 'XS')], default='xl', max_length=50, null=True),
        ),
    ]
