# Generated by Django 2.2.3 on 2021-08-02 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0007_auto_20210729_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Consecutive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('quanty', models.CharField(max_length=7)),
                ('discount', models.CharField(max_length=3)),
                ('fecha', models.CharField(default=datetime.date(2021, 8, 2), max_length=10)),
                ('condition', models.CharField(default='received', max_length=20)),
            ],
        ),
    ]
