# Generated by Django 2.2.3 on 2021-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0009_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='methodPaymet',
            field=models.CharField(default='Contra Entrega', max_length=40),
        ),
    ]
